# Example Apache httpd.conf for auditing
ServerRoot "/etc/httpd"
Listen 80
ServerTokens Full
ServerSignature On
TraceEnable On
SSLProtocol all

DocumentRoot "/var/www/html"
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride None
</Directory>
